# Copyright (c) 2026 Bryce M. Westheimer
# SPDX-License-Identifier: BSD-3-Clause

"""
PDB file writer with fragments as chains/models.

This module provides functions for writing PDB files with fragment information
encoded as separate chains or models.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from autofragment.core.types import Fragment

# Element to atomic number mapping for coordinate formatting
_ELEMENT_TO_Z = {
    "H": 1, "He": 2, "Li": 3, "Be": 4, "B": 5, "C": 6, "N": 7, "O": 8,
    "F": 9, "Ne": 10, "Na": 11, "Mg": 12, "Al": 13, "Si": 14, "P": 15,
    "S": 16, "Cl": 17, "Ar": 18, "K": 19, "Ca": 20,
}

# Chain ID options
_CHAIN_IDS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"


def write_pdb_fragments(
    fragments: List[Fragment],
    filepath: Union[str, Path],
    mode: str = "chains",
    title: str = "Generated by AutoFragment",
    residue_name: str = "FRG",
    interfragment_bonds: Optional[List[Dict[str, Any]]] = None,
) -> None:
    """
    Write PDB file with fragments as chains or models.

    Parameters
    ----------
    fragments : list
        List of Fragment objects.
    filepath : str or Path
        Output file path.
    mode : str, optional
        How to encode fragments:
        - "chains": Each fragment is a separate chain (A, B, C, ...)
        - "models": Each fragment is a separate MODEL
        - "residues": Each fragment is a separate residue
        Default is "chains".
    title : str, optional
        Title for TITLE record.
    residue_name : str, optional
        Residue name for atoms. Default is "FRG".

    Examples
    --------
    >>> from autofragment.core import Fragment
    >>> frags = [Fragment(id="W1", symbols=["O", "H", "H"], geometry=[0,0,0, 1,0,0, -1,0,0])]
    >>> write_pdb_fragments(frags, "fragments.pdb", mode="chains")
    """
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)

    if mode == "chains":
        _write_pdb_chains(fragments, path, title, residue_name, interfragment_bonds)
    elif mode == "models":
        _write_pdb_models(fragments, path, title, residue_name)
    elif mode == "residues":
        _write_pdb_residues(fragments, path, title, residue_name, interfragment_bonds)
    else:
        raise ValueError(f"Unknown mode: {mode}. Use 'chains', 'models', or 'residues'.")


def _format_pdb_atom(
    serial: int,
    atom_name: str,
    residue_name: str,
    chain_id: str,
    res_seq: int,
    x: float,
    y: float,
    z: float,
    element: str,
    occupancy: float = 1.0,
    temp_factor: float = 0.0,
) -> str:
    """
    Format a PDB ATOM record.

    Returns
    -------
    str
        Formatted PDB ATOM line (80 characters).
    """
    # Atom name formatting: 4 chars, left-justified for 2-char elements
    if len(element) == 2 or len(atom_name) >= 4:
        atom_name_fmt = f"{atom_name:<4s}"
    else:
        atom_name_fmt = f" {atom_name:<3s}"

    line = (
        f"ATOM  {serial:5d} {atom_name_fmt}{residue_name:>3s} {chain_id:1s}"
        f"{res_seq:4d}    {x:8.3f}{y:8.3f}{z:8.3f}"
        f"{occupancy:6.2f}{temp_factor:6.2f}          {element:>2s}  "
    )

    return line


def _write_pdb_chains(
    fragments: List[Fragment],
    filepath: Path,
    title: str,
    residue_name: str,
    interfragment_bonds: Optional[List[Dict[str, Any]]] = None,
) -> None:
    """Write PDB with fragments as separate chains."""
    with open(filepath, "w") as f:
        # Header
        f.write(f"TITLE     {title}\n")
        f.write("REMARK   Generated by AutoFragment\n")
        f.write(f"REMARK   {len(fragments)} fragments as chains\n")

        # Track (fragment_id, local_index) -> serial for CONECT records
        atom_serial_map: Dict[tuple, int] = {}

        serial = 1
        for frag_idx, frag in enumerate(fragments):
            chain_id = _CHAIN_IDS[frag_idx % len(_CHAIN_IDS)]
            coords = frag.get_coords()

            for i, symbol in enumerate(frag.symbols):
                x, y, z = coords[i]
                atom_name = f"{symbol}{i+1}"[:4]

                atom_serial_map[(frag.id, i)] = serial

                line = _format_pdb_atom(
                    serial=serial,
                    atom_name=atom_name,
                    residue_name=residue_name[:3],
                    chain_id=chain_id,
                    res_seq=frag_idx + 1,
                    x=x, y=y, z=z,
                    element=symbol,
                )
                f.write(line + "\n")
                serial += 1

            # TER record at end of chain
            f.write(f"TER   {serial:5d}      {residue_name:>3s} {chain_id:1s}{frag_idx+1:4d}\n")
            serial += 1

        # CONECT records for interfragment bonds
        if interfragment_bonds:
            for bond in interfragment_bonds:
                key1 = (bond["fragment1_id"], bond["atom1_index"])
                key2 = (bond["fragment2_id"], bond["atom2_index"])
                if key1 in atom_serial_map and key2 in atom_serial_map:
                    s1 = atom_serial_map[key1]
                    s2 = atom_serial_map[key2]
                    f.write(f"CONECT{s1:5d}{s2:5d}\n")

        f.write("END\n")


def _write_pdb_models(
    fragments: List[Fragment],
    filepath: Path,
    title: str,
    residue_name: str,
) -> None:
    """Write PDB with fragments as separate MODELs."""
    with open(filepath, "w") as f:
        f.write(f"TITLE     {title}\n")
        f.write("REMARK   Generated by AutoFragment\n")
        f.write(f"REMARK   {len(fragments)} fragments as MODELs\n")

        for frag_idx, frag in enumerate(fragments):
            model_num = frag_idx + 1
            f.write(f"MODEL     {model_num:4d}\n")

            coords = frag.get_coords()
            for i, symbol in enumerate(frag.symbols):
                x, y, z = coords[i]
                atom_name = f"{symbol}{i+1}"[:4]

                line = _format_pdb_atom(
                    serial=i + 1,
                    atom_name=atom_name,
                    residue_name=residue_name[:3],
                    chain_id="A",
                    res_seq=1,
                    x=x, y=y, z=z,
                    element=symbol,
                )
                f.write(line + "\n")

            f.write("ENDMDL\n")

        f.write("END\n")


def _write_pdb_residues(
    fragments: List[Fragment],
    filepath: Path,
    title: str,
    residue_name: str,
    interfragment_bonds: Optional[List[Dict[str, Any]]] = None,
) -> None:
    """Write PDB with fragments as separate residues."""
    with open(filepath, "w") as f:
        f.write(f"TITLE     {title}\n")
        f.write("REMARK   Generated by AutoFragment\n")
        f.write(f"REMARK   {len(fragments)} fragments as residues\n")

        atom_serial_map: Dict[tuple, int] = {}

        serial = 1
        for frag_idx, frag in enumerate(fragments):
            # Use fragment ID as residue name if short enough
            res_name = frag.id[:3] if len(frag.id) <= 3 else residue_name
            coords = frag.get_coords()

            for i, symbol in enumerate(frag.symbols):
                x, y, z = coords[i]
                atom_name = f"{symbol}{i+1}"[:4]

                atom_serial_map[(frag.id, i)] = serial

                line = _format_pdb_atom(
                    serial=serial,
                    atom_name=atom_name,
                    residue_name=res_name.upper(),
                    chain_id="A",
                    res_seq=frag_idx + 1,
                    x=x, y=y, z=z,
                    element=symbol,
                )
                f.write(line + "\n")
                serial += 1

        f.write("TER\n")

        # CONECT records for interfragment bonds
        if interfragment_bonds:
            for bond in interfragment_bonds:
                key1 = (bond["fragment1_id"], bond["atom1_index"])
                key2 = (bond["fragment2_id"], bond["atom2_index"])
                if key1 in atom_serial_map and key2 in atom_serial_map:
                    s1 = atom_serial_map[key1]
                    s2 = atom_serial_map[key2]
                    f.write(f"CONECT{s1:5d}{s2:5d}\n")

        f.write("END\n")
