# Copyright (c) 2026 Bryce M. Westheimer
# SPDX-License-Identifier: BSD-3-Clause

"""
XYZ file writer with fragment markers.

This module provides functions for writing XYZ files with fragment information
encoded in comments.
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List, Optional, Union

from autofragment.core.types import Fragment


def write_xyz_fragments(
    fragments: List[Fragment],
    filepath: Union[str, Path],
    comment: Optional[str] = None,
    include_fragment_comments: bool = True,
    include_summary: bool = True,
) -> None:
    """
    Write XYZ file with fragment markers in comments.

    Parameters
    ----------
    fragments : list
        List of Fragment objects.
    filepath : str or Path
        Output file path.
    comment : str, optional
        Custom comment line. If None, generates summary.
    include_fragment_comments : bool, optional
        Add fragment ID comments between atoms. Default is True.
    include_summary : bool, optional
        Include fragment summary in header comment. Default is True.

    Notes
    -----
    Fragment information is encoded in the comment line as:
    "Fragment: F1(3 atoms) F2(3 atoms) ..."

    Examples
    --------
    >>> from autofragment.core import Fragment
    >>> frags = [
    ...     Fragment(id="W1", symbols=["O", "H", "H"], geometry=[0,0,0, 1,0,0, -1,0,0]),
    ...     Fragment(id="W2", symbols=["O", "H", "H"], geometry=[3,0,0, 4,0,0, 2,0,0])
    ... ]
    >>> write_xyz_fragments(frags, "water_dimer.xyz")
    """
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)

    # Count total atoms
    total_atoms = sum(f.n_atoms for f in fragments)

    # Build comment line
    if comment is None:
        if include_summary:
            frag_info = " ".join(f"{f.id}({f.n_atoms} atoms)" for f in fragments)
            comment = f"Fragments: {frag_info}"
        else:
            comment = "Generated by AutoFragment"

    with open(path, "w") as f:
        # Atom count
        f.write(f"{total_atoms}\n")

        # Comment line
        f.write(f"{comment}\n")

        # Atoms with optional fragment markers
        for frag in fragments:
            if include_fragment_comments:
                # Add fragment marker as comment (XYZ format allows extra columns)
                pass  # We'll mark in coords instead

            coords = frag.get_coords()
            for i, symbol in enumerate(frag.symbols):
                x, y, z = coords[i]
                if include_fragment_comments:
                    f.write(f"{symbol:2s}  {x:15.10f}  {y:15.10f}  {z:15.10f}  # {frag.id}\n")
                else:
                    f.write(f"{symbol:2s}  {x:15.10f}  {y:15.10f}  {z:15.10f}\n")


def write_xyz_extended(
    fragments: List[Fragment],
    filepath: Union[str, Path],
    properties: Optional[Dict[str, List[float]]] = None,
    lattice: Optional[List[List[float]]] = None,
) -> None:
    """
    Write extended XYZ file with fragment and property information.

    Parameters
    ----------
    fragments : list
        List of Fragment objects.
    filepath : str or Path
        Output file path.
    properties : dict, optional
        Per-atom properties to include (e.g., {"charge": [...], "force_x": [...]}).
    lattice : list, optional
        3x3 lattice vectors for periodic systems.

    Notes
    -----
    Extended XYZ format includes properties in the comment line and
    additional columns for per-atom data.
    """
    path = Path(filepath)
    path.parent.mkdir(parents=True, exist_ok=True)

    total_atoms = sum(f.n_atoms for f in fragments)

    # Build comment line with properties spec
    comment_parts = []

    if lattice:
        lat_str = " ".join(str(x) for row in lattice for x in row)
        comment_parts.append(f'Lattice="{lat_str}"')

    # Properties specification
    props_spec = ["species:S:1", "pos:R:3"]
    prop_names = []

    if properties:
        for name, values in properties.items():
            props_spec.append(f"{name}:R:1")
            prop_names.append(name)

    # Add fragment as property
    props_spec.append("fragment:S:1")

    comment_parts.append(f'Properties={":".join(props_spec)}')
    comment = " ".join(comment_parts)

    # Collect all property values
    all_frags = []
    for frag in fragments:
        for i in range(frag.n_atoms):
            all_frags.append(frag.id)

    with open(path, "w") as f:
        f.write(f"{total_atoms}\n")
        f.write(f"{comment}\n")

        atom_idx = 0
        for frag in fragments:
            coords = frag.get_coords()
            for i, symbol in enumerate(frag.symbols):
                x, y, z = coords[i]
                parts = [f"{symbol:2s}", f"{x:15.10f}", f"{y:15.10f}", f"{z:15.10f}"]

                # Add properties
                if properties:
                    for name in prop_names:
                        if atom_idx < len(properties[name]):
                            parts.append(f"{properties[name][atom_idx]:15.10f}")
                        else:
                            parts.append("0.0")

                # Add fragment
                parts.append(frag.id)

                f.write("  ".join(parts) + "\n")
                atom_idx += 1
